### ISSUE TITLE
Can't launch server

### ISSUE THREAD

**Issue by raulsperoni** [larueli/decidim-nonroot#1]
Hi! First of all thank you, I haven't found anything on how to run Decidim on openshift.

I'm having trouble running your built image, I think is related to permissions in decidim_app folder, nginx and passport.

I've also tried to build the image myself and i'm getting an error on:

- chmod -R g=rwx /usr/local/bundle/gems/omniauth-cas* (that folder does not exist)
- nginx: [alert] Unable to start Phusion Passenger: Support binary PassengerAgent not found

Could you help me?
Thank you!

[EDIT]
This error "Unable to start Phusion Passenger" was caused by wrong passenger version in nginx.conf. Changing to 6.0.6 gives me a new error in the browser:

Incomplete response received from application

**Comment by larueli** [comment]
Hello !

Thanks for your interest, I'm looking into this quickly. I haven't done any work in this repo for month now, it's time to go back to it !
I'll keep you updated ;)

**Comment by larueli** [comment]
Hello @raulsperoni, I fixed the issue. You should try now, I put an example of a docker-compose.yml in the repo, it can help you to configure your deploymentconfig in OpenShift.

The exposed ports have changed, it's now only 3000 and no ssl provided. You have two volumes, one for config, one for uploads. You can find more info in the README.

**Comment by raulsperoni** [comment]
Thank you! great work! I forked this project and will be using it, is very useful.
Did you removed the etherpad config and admin user sections from entrycheck for some reason?

**Comment by larueli** [comment]
I removed these config because

* if Decidim decides to change how we should configure Etherpad / Admin creation / ... I have to change it also, and this can lead to a very long delay since I don't have much time to work on this project.
* The config folder is now a volume

The decidim doc about [installation](https://docs.decidim.org/en/install/) and [configuration](https://docs.decidim.org/en/configure/) is very complete and will help those who need to configure some functions.

More info about [etherpad config](https://docs.decidim.org/en/services/etherpad/).

And I removed the admin section because you can do it directly from the container and it's only needed once :
```
bin/rails console
> email = "test@email.com"
> password = "mystrongpassword"
> user = Decidim::System::Admin.new(email: email, password: password, password_confirmation: password)
> user.save!
```

Are you okay with that ? I thought it was a good idea to remove it.
