### ISSUE TITLE
Decidim initiatives error

### ISSUE THREAD

**Issue by raulsperoni** [larueli/decidim-nonroot#4]
Hello, there seems to be a problem with decidim initiatives. When a new user register there is an 500 error related to a column not found in database. After this, decidim does not recorvers. Is this happening to you?

Completed 500 Internal Server Error in 46ms (ActiveRecord: 2.5ms)
Error during failsafe response: PG::UndefinedColumn: ERROR:  column decidim_initiatives.decidim_author_type does not exist
LINE 1: ...m_initiatives".* FROM "decidim_initiatives" WHERE "decidim_i...

Thank you.

**Comment by raulsperoni** [comment]
I've opened an issue on decidim repo https://github.com/decidim/decidim/issues/6730

**Comment by oliverbarnes** [comment]
In trying to help @raulsperoni with this, I gave the [docker image](https://hub.docker.com/r/larueli/decidim-nonroot) a spin, and it does look like the migrations for initiatives don't include the decidim_author_type field. I then peeked at the generated Gemfile.lock, and it turns out an old version of the initiatives gem gets installed: decidim-initiatives (0.13.0.pre1).

This seems to be because the Dockerfile appends the gem to the Gemfile without a version specified: echo "gem 'decidim-initiatives'" >> Gemfile.

Decidim uses semantic versioning across core gems, so if you want the build to work with decidim 0.22.0, decidim-initiatives also needs to be at 0.22.0. Same goes for decidim-consultations

**Comment by raulsperoni** [comment]
Hey @oliverbarnes thank you so much! I asumed that if you didn't specified a version it would use the latest one. I will test this. Thanks!

**Comment by oliverbarnes** [comment]
It is weird the old version got installed for decidim-initiatives, it might have been at the time the image was built, that was just the version lying around. decidim-consultations does have the correct version, fwiw

**Comment by raulsperoni** [comment]
It is weird because i also built the image locally, re building now.
